### ISSUE TITLE
Bugs in bottleneck distance computation

### ISSUE THREAD

**Issue by lizliz** [scikit-tda/persim#28] opened 2020-01-09 20:50 UTC
I'm having an issue with the bottleneck distance function, haven't dug into the code to figure out what's up but hoping that someone can hunt it down.

First issue: passing an empty diagram (in the form of an empty array) just throws an error.

Second issue: I seem to have created multiple instances of diagrams whose distance to themselves are non-zero:

```
dgmA = np.array([[0.11371516, 4.45734882]])
bottleneck(dgmA,dgmA)
```
returns 2.17181683. First guess is that this is caused by diagrams with a single point but can't be sure.

**Comment by ctralie** [comment] 2020-01-09 20:56
Ack, sorry for the trouble! I thought I fixed this already, but it's
possible that either there's an additional bug or that the most recent
version. Hasn't been pushed. I'm traveling at the moment but will have a
look asap.

As a side note, I have been waiting to create a pure python implementation
of Hera for some time...

**Comment by sauln** [comment] 2020-01-10 20:56
It looks like a fix for diagrams with multiple points was released in August. I confirmed that still works, but the case of single point diagrams does not work.

@ctralie you think this can be fixed at the algorithm level? A simple short-circuit would be easy to implement.  

I've started a PR with a failing test highlighting the issue here #29.

**Comment by ctralie** [comment] 2020-01-11 20:00
Thanks for doing that @sauln, I will have a look today

**Closed** 2020-01-11 22:12 UTC

**Comment by ctralie** [comment] 2020-01-11 22:15
Thank you for helping to make the code better @lizliz , and my apologies again for the bug.  It should be good now.  We will let you know when a new version is up on pypi.  Though before we push to pypi, I will also work to handle empty diagrams more gracefully
