### ISSUE TITLE
plot diagram only in blue color (no orange)

### ISSUE THREAD

**Issue by tmelorc** [scikit-tda/persim#32] opened 2020-02-06 13:37 UTC
First of all, since I was not able to install via `pip install persim`, I got the source `scikit-tda-master.zip` and run the `setup.py`. Also, I'm using **Python 2.7** with `matplotlib` version 1.5.1.

The minimal code below works except by the fact that the diagrams in both dimensions are in blue, not blue/orange, like in documentation. 

**MWE**
```
import numpy as np
import matplotlib.pyplot as plt 
from ripser import Rips
from persim import plot_diagrams
import matplotlib
print('my matplotlib is', matplotlib.__version__) # my matplotlib is 1.5.1

pts = np.array([ [0, 0], [.8, 0], [.6, 1], [0, 1]  ])
rips = Rips(maxdim=1, coeff=2, thresh=2)
diagramas = rips.fit_transform(pts)
print(diagramas[0])
print(diagramas[1])

plot_diagrams(diagramas, show=True)
```
See the screenshot.

![Figure 1_175](https://user-images.githubusercontent.com/15181573/73941492-23d65a00-48cc-11ea-855b-b937c660a220.png)

**Comment by tmelorc** [comment] 2020-02-06 18:24
Just to inform, it works well with Python 3.8 (I've just installed).

**Comment by sauln** [comment] 2020-02-06 19:32
Very strange! not sure what the issue is here.  Since Python 2.7 is EOL, we won't be fixing any bugs on it.  Glad that 3.8 worked,

**Closed by sauln** 2020-02-06 19:32 UTC

**Comment by tmelorc** [comment] 2020-02-06 19:34
> Very strange! not sure what the issue is here. Since Python 2.7 is EOL, we won't be fixing any bugs on it. Glad that 3.8 worked,

Yes. After hours trying to figure out what was happening I decided to install 3.8. Maybe it could work for 3.7 or 3.6, I don't know. 
Regards.
